version: '3.5'

services:
  go_server:
    # build: ../container
    image: go_server
    networks:
      - traefik-proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.go_server_router.entrypoints=web"
        - "traefik.http.routers.go_server_router.rule=Host(`assignment-2-go-server`)"
        - "traefik.http.services.go_server_service.loadbalancer.server.port=8080"

networks:
  traefik-proxy:
    external: true
