version: '3.5'

services:
  traefik:
    image: traefik:v2.0
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - --api.insecure=true
      - --api.dashboard=true
      # - --api.debug=true
      # - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.network=traefik-proxy
      - --entrypoints.web.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.entrypoints=web"
        - "traefik.http.routers.api.service=api@internal"

networks:
  traefik-proxy:
    driver: overlay
    external: true
