version: '3.5'

services:
  go_server:
    image: go_server
    # ports:
    #   - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go_server_router.entrypoints=web"
      - "traefik.http.routers.go_server_router.rule=Host(`assignment-2-go-server`)"
      - "traefik.http.services.go_server_service.loadbalancer.server.port=8080"
  traefik:
    image: traefik:v2.0
    ports:
      - "8080:8080"
      - "80:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../load_balancer:/etc/traefik
